# shellcheck shell=bash disable=SC2034  # sourced; variables are used by the callers
# Sourced by up.sh, down.sh, run-collector.sh, open-trx.sh, load.sh.
# The docker CLI honours DOCKER_HOST (ssh://ggt-docker), so every docker
# build/run/cp/exec below goes to that daemon when it is set.
FIX_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
NET=jjsong-ggt-mysql-net
PRIMARY=jjsong-ggt-mysql-primary
REPLICA=jjsong-ggt-mysql-replica
M57=jjsong-ggt-mysql-57
IMG80=jjsong-ggt-mysql-ubuntu80:1
IMG57=jjsong-ggt-mysql-57:1
ALL_CONTAINERS="$PRIMARY $REPLICA $M57"
# Throwaway credentials, generated by up.sh, never in the repo.
SECRETS="${GGT_MYSQL_SECRETS:-$HOME/.claude/lab-secrets/jjsong-ggt-mysql.env}"

die() { echo "!! $*" >&2; exit 1; }
say() { echo ">> $*" >&2; }
# shellcheck source=/dev/null
load_secrets() { [ -r "$SECRETS" ] || die "no secrets file $SECRETS (run up.sh)"; . "$SECRETS"; }
exists()  { docker container inspect "$1" >/dev/null 2>&1; }
running() { [ "$(docker container inspect -f '{{.State.Running}}' "$1" 2>/dev/null)" = true ]; }
is57()    { [ "$1" = "$M57" ]; }

# root_sql CONTAINER -> the in-container root client, SQL on stdin. The Ubuntu
# package's root@localhost is auth_socket (no password); the 5.7 root has one,
# kept in the container's /root/.ggt-root.cnf (mode 600), written by up.sh.
root_sql() {
    if is57 "$1"; then docker exec -i "$1" mysql --defaults-extra-file=/root/.ggt-root.cnf -N "${@:2}"
    else docker exec -i "$1" mysql -N "${@:2}"; fi
}
